_sass/_buttons.scss, _sass/_layout.scss, _sass/_navbar.scss, css/main.scss
=> Design tweaks

_includes/header.html, _sass/_navbar.scss
=> Nav bar fixes

_includes/scripts.html, _layouts/default.html
=> Replace GA with GTM

_data/libraries.yml, index.html
=> Add java-sparkpost links

index.html
Fixes #66
I modified the existing example based on the transmissions example from https://github.com/SparkPost/node-sparkpost/blob/master/docs/resources/transmissions.md. Let me know if it should be modified.
=> Updated NodeJS sample code.

lab/index.html
Resolves #68
Let me know if we need anything else.
=> Updated Mini-hack 1 for drawing

_config.yml, _includes/footer.html
Resolves #72
Footer now uses config values.
=> Changed Twitter account Resolves #72

Rakefile, _config.yml, index.html
=> Added Heroku blog post to the front page

_data/libraries.yml, index.html
Added Ruby and Elixir to the list of client libraries. Added examples for Ruby, Java, Go, and Elixir.
There is currently no devicon for Elixir but I have put in a request for one to be added.
=> Updated client library list and added examples

index.html
I also modified the to addresses to include `+libName`.
=> Added csharp example to the front page

Gemfile.lock, _data/blog_posts.yml, _faqs/customize_template.md, _faqs/dynamic_template_subject.md
I rebased this from mary's branch against this one, should be ready to merge now w/o conflicts.
=> Updated faq

_data/blog_posts.yml, _faqs/dkim_verification.md, _faqs/get_transmissions.md, _faqs/reply_to_address.md, _faqs/suspended.md
- added 2 more FAQs and updated the suspension question w/more detail from Autumn
- updated the blogpost list to include the latest 5 posts
=> updated FAQ & blogpost list

README.md
I got an error when trying to get it running locally, this fixes that error for others if they also run into it.
=> Added note about openssl error

_layouts/default-grid.html, _layouts/faq.html, css/main.scss
To do this, I added new default grid layout that extends default layout, but has the row/centering set up for you. For a quick new page you can use `layout: default-grid` and just put your content in starting with an `h1` or whatever.
=> Fixing individual FAQ page style, 

_contributors/aimee_knight.md, _contributors/aydrian_howard.md, _contributors/benjamin_dean.md, _contributors/chris_wilson.md, _contributors/david_rowley.md, _contributors/mary_thengvall.md, _contributors/rich_leland.md, _layouts/contributor.html, _layouts/faq.html, _layouts/video.html, _plugins/to_gravatar.rb
The default gravatar image will be displayed if no email or no image exists for the email.
=> Added gravatar plugin so no more manually creating the gravatar hash

_faqs/post_to_endpoint_failed.md
Getting this question a lot, it seems.
=> Added faq for post to endpoint failed

_data/libraries.yml, index.html
Removed library from the datafile and removed the code example.
=> Remove references to the ruby library

_data/blog_posts.yml, _data/events.yml
updated blogposts & events listings
=> General update

_data/blog_posts.yml, _data/events.yml
updated events & blogposts listings
=> Events blogposts 62816

_data/blog_posts.yml, _data/events.yml
=> Blog events 9916

_data/blog_posts.yml, _data/events.yml
added 9/23 blogpost & SD Hacks
=> 9 23 blogpost event

index.html
PHP sample is now correct for php-sparkpost 2.0.3.
Also fixed the syntax highlighting.
=> Fixed PHP sample code

_hackathons/SDHacks2016.html, hackathons/index.html
Also, marked SD Hacks as past.
=> Added sample applications to hackathons page

_data/blog_posts.yml, _data/events.yml
added Friday blogpost & changed "Manhattan, NY" to "NYC, NY" for BrooklynJS
=> Blogposts 102116

_data/blog_posts.yml, _data/events.yml
added 4 relevant blogposts & AWS coffee w/Aydrian
=> Blogposts 1142016

_data/blog_posts.yml, _data/events.yml
changed event status to "past" for MLH, BrooklynJS, & Nodevember.
added blogposts from the last 2 weeks.
=> Events blogposts 1128

_data/blog_posts.yml, _data/events.yml
added Intern update
added BrickHack 2017
=> 12 2 blogpost & event

_data/blog_posts.yml, _data/events.yml
added 5 new events, plus Friday blogpost
=> Jan 6 blogposts & events

_data/blog_posts.yml, _data/events.yml
added Jan20 blogpost
changed BrooklynJS & Elixir meetups to past
=> Jan20 blog events

_data/blog_posts.yml, _data/events.yml
- added Rich's Guide to Using SparkPost with Python blogpost
- marked ManhattanJS & BrickHack as past events
=> Blogs events 2-13

_data/blog_posts.yml, _data/events.yml
- added Building Email Chatbots with SparkPost blogpost
- changed Codeland status to `past`
=> 4/24 blogpost & events updates

_data/blog_posts.yml, _data/events.yml
- added Slack Emojis blogpost
- changed QCon to "past"
- added July WaffleJS & August QueensJS
- added July SFHTML5 link & changed to "future"
=> Events blogs 63017

content/api/account.apib
=> Account Reference Migration

content/api/smtp-api.apib
This isn't for a content refactor -- just moving the content over and using the data structure format.
=> Migrate smtp-api.apib

package-lock.json, package.json, src/components/Layout/index.css.js, src/components/Layout/index.js
Looks like we didn't ship Source Code Pro with the site. This PR adds it in.
=> added Source Code Pro

content/api/ab-testing.apib, content/api/account.apib, content/api/inbound-domains.apib, content/api/ip-pools.apib, content/api/message-events.apib, content/api/metrics.apib, content/api/recipient-lists.apib, content/api/relay-webhooks.apib, content/api/sending-domains.apib, content/api/sending-ips.apib, content/api/subaccounts.apib, content/api/suppression-list.apib, content/api/templates.apib, content/api/tracking-domains.apib, content/api/transmissions.apib, content/api/webhooks.apib, package-lock.json, package.json, src/components/api/parts/Request.js, src/components/api/parts/Transition.js
per Slack convo with Avi 🎉, this helps out with any apis that have a `/api/labs` prefix instead of an `/api/v1` prefix
=> Puts onus of maintaining version state on .apib files, instead of components

content/api/message-events.apib, content/api/webhooks.apib, plugins/gatsby-transformer-api-blueprint/data-structures.js, src/components/api/components/BlockMarkdown/DataStructure.js, src/components/api/components/BlockMarkdown/MessageEvents.js, src/components/api/components/BlockMarkdown/WebhookEvents.js, src/components/api/components/BlockMarkdown/index.js
Mimic React components in our Markdown.
=> Mimic React

content/api/suppression-list.apib
=> Suppression Sort Param Fix

content/api/inbound-domains.apib
=> Enterprise inbound fix

content/api/template-language.apib, package-lock.json, plugins/gatsby-plugin-algolia/package-lock.json, plugins/gatsby-source-sparkpost-api/package-lock.json, plugins/gatsby-transformer-api-blueprint/package-lock.json
=> TR-457 Added section on link extraction

content/api/tracking-domains.apib
=> TR-520 updated for new tracking domains API error codes

content/api/transmissions.apib
=> TR-304 fixed bad merge

src/components/CodeSamples/index.js
=> Added missing backslash in curl example

content/api/account.apib
=> AC-441 adds sandbox usage to individual account GET

content/api/recipient-validation.apib, content/api/table-of-contents.json
=> EO-358 RV docs

content/api/table-of-contents.json, package-lock.json
This PR reorganizes the table of contents so that Snippets is next to Template Language.
=> Reorganize table of contents

content/api/ab-testing.apib
Added banner for single recipient.
=> ESCSP-2705 added banner for single recipient

content/api/relay-webhooks.apib, package-lock.json, src/components/CodeSamples/index.js
=> SD-400 initial commit for oauth updates

content/api/templates.apib
=> TR-884 added content-previewer endpoint docs

content/api/events.apib, package-lock.json
=> SA-514: documenting event-api search parameter 'event_ids'

content/api/recipient-validation.apib
=> document free field

content/api/relay-webhooks.apib, content/api/webhooks.apib, package-lock.json, package.json
=> Call out Webhooks port specification

content/api/events-ingest.apib, package-lock.json
=> Adding api documentation for events ingest GETs

content/api/ip-pools.apib, package-lock.json
=> SD-1252 added shared pool overflow pool to ip-pools api docs

content/api/events.apib
=> SE-299 Updated documentation with new datetime format

content/api/relay-webhooks.apib
=> SD-1282 updated relay webhook docs to include another 400 error

content/api/transmissions.apib
=> TR-2126 Document maximum days in the future for scheduled transmissions

content/api/templates.apib, package-lock.json
=> TR-2252 change template content size to 5MB

content/api/data-privacy.apib, package-lock.json
=> AC-1396 clarified data privacy api docs for subaccounts

content/api/suppression-list.apib
=> adding query param description_strict to suppression list endpoint

package-lock.json, package.json
=> TR-2290 roll back sharp update

package-lock.json
=> TR-2290 revert package-lock

content/api/webhooks.apib, package-lock.json
Adding descriptions for returned values on `GET` to `/api/v1/webhooks/{id}/batch-status`
=> SE-505 Updating `GET` Batch status data structure descriptions

content/api/metrics.apib
=> SA-1489 update precision validation section for metrics

content/api/index.apib, content/api/transmissions.apib, package-lock.json, package.json
=> ESCSP-3976 rate limit doc

content/api/transmissions.apib
=> TR-2577 made the notice a banner

content/api/template-language.apib
=> TR-2369 Adding snippet information on usage

content/api/index.apib, package-lock.json, src/components/api/parts/ResourceGroup.js
=> Change getpostman.com ~> postman.com

content/api/recipient-validation.apib
=> Tr 2614 adding delivery confidence in RV

content/api/events-ingest.apib, package-lock.json
=> Updating ingest documentation to specify max age of valid events

content/api/metrics.apib, package-lock.json, package.json
=> SA-1471 updates docs for timeseries precision rounding

content/api/metrics.apib
Reverts SparkPost/developers.sparkpost.com#419
=> Revert "SA-1471 fix formatting in timeseries precision rounding table"

content/api/metrics.apib, package-lock.json, package.json
Reverts SparkPost/developers.sparkpost.com#417
=> Revert "SA-1471 updates docs for timeseries precision rounding"

content/api/recipient-validation.apib
=> TR-2839 add special character encoding documentation to RV single

content/api/data-privacy.apib, content/api/metrics.apib, content/api/sending-domains.apib, content/api/smtp.apib, content/api/subaccounts.apib, content/api/suppression-list.apib, content/api/templates.apib, content/api/tracking-domains.apib, content/api/transmissions.apib
Replaces `master account` with `primary account`
Can be verified via netlify's build: https://deploy-preview-429--developers-sparkpost.netlify.app/api/
=> Replace 'master account' with 'primary account'

content/api/subaccounts.apib, package-lock.json, package.json
=> AC-1852 add documentation for subaccount options

.github/workflows/codeql-analysis.yml
- Adds GitHub action for CodeQL analysis
- Derived from the [2web2ui implementation](https://github.com/SparkPost/2web2ui/blob/master/.github/workflows/codeql-analysis.yml)
=> FE-1331 - Adds CodeQL analytics GitHub Action

content/api/metrics.apib, package-lock.json
https://sparkpost.atlassian.net/browse/SA-1932
Descriptions from product:
https://docs.google.com/presentation/d/1igD-ewcOb99zq585GRuZEzwr805xHUCfbGIjqMvg3xE/edit#slide=id.p
=> SA-1932 document new metrics endpoint for inbox-rate

content/api/metrics.apib, package-lock.json
=> SA-2191 Metrics support aggregate by Mailbox Provider

content/api/metrics.apib
=> SA-2190 Metrics support advanced filters for Region

content/api/metrics.apib
=> Added docs for mailbox-provider-regions listing endpoint

content/api/metrics.apib
=> Added advanced filter keys for mailbox_provider

content/api/seed-list.apib
=> SA-2307 change plain text to label with link

content/api/events.apib
I removed the new label for the Events API... it's not that new any more :)
=> Events isn't that new

algolia/momentum.js, gatsby/onCreateNode.js, gatsby/onPostBootstrap.js, plugins/gatsby-source-sparkpost-api/gatsby-node.js, plugins/gatsby-transformer-api-blueprint/data-structures.js, plugins/gatsby-transformer-api-blueprint/on-node-create.js, src/components/api/components/BlockMarkdown/EventsTable.js
Addressed the code scanning alerts. Mostly unused variables.
=> FE-1402: Addressed code scanning alerts

.github/workflows/security-badger.yml
- Verify Security Badger config is valid (compare with `2web2ui`)
- Verify `GRAPHQL_GITHUB_API_ACCESS_TOKEN` and `SECURITY_BADGER_SLACK_WEBHOOK_URL` secrets were added to the repo
=> FE-1444 - Incorporates Security Badger GitHub Action

content/api/smtp.apib
=> - SD-2589: updated recommendation about max number of messages to inject per SMTP connection;

package-lock.json, package.json
[FE-1507](https://sparkpost.atlassian.net/browse/FE-1507)
- Removes use of `auditmated` package
=> FE-1507 - Remove use of 'auditmated' package

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codeql-analysis.yml, README.md, content/api/subaccounts.apib, plugins/gatsby-transformer-api-blueprint/package-lock.json
=> updated readme

content/api/transmissions.apib
=> TR-3159 Limit sandbox domain abuse

content/api/sending-domains.apib
=> Fixed a typo

content/api/index.apib, package-lock.json
Corrected the documentation for using Basic Authentication.
=> updated api docs for basic auth

README.md, content/api/metrics.apib
- Removing all binding references from Metrics API
- Adding M1 Pro troubleshooting to README
=> SAA-58 Remove binding references from metrics api

netlify.toml
- Add CSP Headers
- Created [developers-sparkpost-com](https://sentry.io/organizations/sparkpost/projects/developers-sparkpost-com/?project=6351005&statsPeriod=14d) project on Sentry to monitors CSP violations
=> FE-1641: Add CSP header

netlify.toml
- Add eval on CSP `script-src` list
- Patch for https://github.com/SparkPost/developers.sparkpost.com/pull/517
=> FE-1641: Add eval on script-src CSP

netlify.toml
- Add font exception (sentry issues: [DEVELOPERS-SPARKPOST-COM-J](https://sentry.io/organizations/sparkpost/issues/3234398425/?project=6351005&query=is%3Aunresolved+logger%3Acsp&statsPeriod=14d), [DEVELOPERS-SPARKPOST-COM-H](https://sentry.io/organizations/sparkpost/issues/3233948080/?project=6351005&query=is%3Aunresolved+logger%3Acsp&statsPeriod=14d))
- Patch for https://github.com/SparkPost/developers.sparkpost.com/pull/517
=> FE-1641: Add fonts exceptions

content/api/webhooks.apib, plugins/gatsby-source-sparkpost-api/package-lock.json, plugins/gatsby-transformer-api-blueprint/package-lock.json
- Adding docs for Event Webhooks' Subaccount Updates
- Adding docs for Event Webhooks' `exception_subaccounts` feature
=> SAA-715 update docs for subaccount update and exception_subaccounts

content/api/events-ingest.apib
=> Updated wrong path of events url in events-ingest docs

netlify.toml
- Updated sentry report-uri to the new MB project
=> Updated sentry report-uri

content/api/index.apib
Verification Steps
- Check if new link is working: https://god.postman.co/run-collection/ee44dcd644445e8bd864?action=collection%2Fimport
=> ESCSP-5960 Fixed Run in Postman link

src/components/api/parts/ResourceGroup.js
How to test:
- Go to /api/*
- Check if all `Run in postman` links are working properly
=> SGA-123 Fix postman link

content/pages/index.js, gatsby-config.js
=> Fix build removing wordpress query

README.md, content/api/template-language.apib
=> TASK-6365: enforce new line behavior with statements in template language documentation

content/api/usage.apib
=> fix format
