SparkPost/developers.sparkpost.com

_includes/header.html, _sass/_layout.scss, _sass/_navbar.scss
Made three changes:
- Changed the in the banner from Ewan's blog post to the same link www.sparkpost.com is using since there is some more information available there.
- Bumped up the size of the font in the banner. For me at least it was looking quite small.
- Changed the top margin of the iframe in which the API code panel appears. This seems to have fixed the problem described in [Slack by Jose][1] whereby the top was chopped off.
[1]: https://msys.slack.com/archives/dev-relations/p1456808711000968
=> Mandrill banner

api/index.html
Will help to avoid encouraging folks to use client-side JS with our API when they won't be able to because of security and CORS settings.
=> Disabled JavaScript code examples

_includes/header.html, _sass/_layout.scss, _sass/_navbar.scss
Did a few things to make the docs more usable while we wait for the new ones:
* Unfixed the header (everywhere, in fact ... maybe we can revisit this with Rich Guy later to see what's best but for now this was the easiest way to fix this issue)
* Removed the Mandrill bar from the API docs page only
* Hid the footer on the API docs page only -- nobody actually intends to get all the way to the bottom of this page, but if you scroll the nav far enough the footer appears and gets in the way big time, not necessary to have the footer on this page imo
=> Making the current docs easier to use today, until new docs are ready

js/redirect.js
This is to support the changes being made in https://github.com/SparkPost/sparkpost-api-documentation-DEV/pull/165
=> Add redirects for subaccounts docs changes

_data/blog_posts.yml, _data/events.yml
- added Topol blogpost
- changed status of Fluent, Velocity, & June SFHTML5
- added July SFHTML5 with "past" status to hide it until meetup.com event is live
=> Blogpost & events 624

content/api/message-events.apib
This puts it more inline with the webhooks samples endpoints, and also eliminates the possibility of these docs becoming out of date as event sample docs changes
=> Update message events samples endpoint responses to be more generic

plugins/gatsby-transformer-api-blueprint/data-structures.js, plugins/gatsby-transformer-api-blueprint/extend-node-type.js, plugins/gatsby-transformer-api-blueprint/package-lock.json, plugins/gatsby-transformer-api-blueprint/package.json
Right now the markdown-only apib files don't have a structured navigation.
This PR adds in that structure so the sidebar is easier to navigate.
**Before**
**After**
=> Fix Markdown-only navigation

content/api/message-events.apib
`datetime` was breaking the rendering of defaults, so update params to be `string` types, and (yay) defaults now show!
=> Fixed markdown for from/to query params in Message Events

src/components/api/components/BlockMarkdown/REPL.js
Removes a CSS rule that was hiding newlines in template HTML examples
=> remove rule that was collapsing multi-line html onto one line

content/api/events-ingest.apib
Updates the label on the Events Ingest API to indicate it's private access only.
=> changes ingest label to private access

content/api/events.apib
Per ESCSP-3724 updates events docs to call specify `from` and `to` are UTC.
=> ESCSP-3724 updates events docs to call specify from and to are UTC

content/api/transmissions.apib, gatsby-config.js, package-lock.json, plugins/gatsby-source-sparkpost-api/gatsby-node.js, plugins/gatsby-transformer-api-blueprint/extend-node-type.js
**To Reproduce**
- Run `npm run boostrap`.  
- This will run `npm install` for the `/plugins`.  This script will appear to "fail".  Please ignore.  The script fails to install "protagonist" which is an optional dependency of "drafter" which is used by the "fury".
- Run `npm run build`.
- It should fail.
- It should have taken a couple minutes and you will see a number of failed requests to Wordpress.  I reduced this noise by only fetching the necessary Wordpress resources.
- The real failure is the "Error parsing blueprint!" pointing to the "ast" field.  It was hard for me to track down more details about this error, so I added some logging to help with debugging.
**The Problem**
- bba29c189f704016bf4941a610db7eb00466a68c introduced a "base type 'including' is not defined in the document" …
=> FE-1202: API docs build is failing due to an error parsing blueprint

content/api/sending-domains.apib
Fixes tiny typo in which the word 'bound' was used instead of 'bounce'.
=> resolve-#408 - Resolve sending domains typo

src/components/Header/Search/index.js
We changed Algolia indices when we migrated the hosting platform of the website. This PR updates the usage of all Algolia indices to their new counterparts.
In order to test:
1. Visit Netlify preview: https://5f8dd5233e49ed0007642b00--developers-sparkpost.netlify.app/
2. Type "getting started" and click on any of the "Documentation" links
3. Expect the link to open www.sparkpost.com instead of sparkpost.kinsta.cloud.
4. Go back and type "continuous integration deployment" and click on any of the "Blog" links.
5. Expect the link to open www.sparkpost.com and not sparkpost.kinsta.cloud.
=> AC-1741 Replace old algolia indices with updated ones

content/api/webhooks.apib
For security purposes webhooks only support ports :80 and :443. This adds a note to the creation endpoint explaining what ports we support.
=> adds explanation of supported ports for webhooks

content/api/account.apib
**EDIT: (From Chris)**
Adding the initial_open_include_alt_attribute boolean account option to the public docs.
ticket: https://sparkpost.atlassian.net/browse/TR-3165
admin API docs PR: https://github.com/SparkPost/sparkpost-admin-api-documentation/pull/553
accounts api PR: SparkPost/accusers-api#848
=> TR-3165 add pulic facing initial_open_include_alt_attribute account option

content/api/smtp.apib
Expand the "options" attribute for smtpapi at https://developers.sparkpost.com/api/smtp/ and notice the inline_css description is not rendering correctly.  
inline_css renders correctly for the transmissions api docs.  I've copied the transmissions inline_css description and used it here.
=> Attempting to fix rendering issue with the inline_css description

content/api/metrics.apib
A customer reported that list parameter types with multiple values are rendered with missing commas. See the attached example from the [Metrics Time Series docs](https://developers.sparkpost.com/api/metrics/#metrics-get-time-series-metrics). This appears to be a rendering issue, since the example values are comma delimited in the markdown docs. While we troubleshoot the rendering issue, I'm removing multiple values from the examples so that customers can copy and paste the examples without issue. I searched the docs and only found list types with multiple values in the Metrics API docs.
=> provides only one value for list parameter request examples

package-lock.json, plugins/gatsby-transformer-api-blueprint/data-structures.js
- Removes [useless conditional](https://github.com/SparkPost/developers.sparkpost.com/security/code-scanning/14?query=ref%3Arefs%2Fheads%2Fmaster) found via GitHub code scanning
=> FE-1505 - Resolve code scanning alert in developers.sparkpost.com

content/pages/index.js, gatsby-config.js, src/components/Card/index.js
[FE-1526](https://sparkpost.atlassian.net/browse/FE-1526)
* Removes references to WP users endpoint
* Removes references to `author` data derived from said endpoint
=> FE-1526 - Fix broken developers.sparkpost.com builds due to unavailable WordPress dependency

content/api/recipient-lists.apib, content/api/templates.apib, content/api/tracking-domains.apib, content/api/transmissions.apib
- Transmissions:
- `ip_pool` case insensitive
- Templates:
- `template_id` case sensitive
- Recipient Lists:
- `id` case sensitive
- Tracking Domains:
- `domain` case sensitive
=> TR-2860 update TR docs to denote case in/sensitivity

content/api/metrics.apib
Adds `job_search` as an industry benchmark category. I also confirmed that the industry list is up to date and correct when compared to the model in the [Metrics API](https://github.com/SparkPost/metrics-api/blob/main/lib/model/inbox-rate.js#L13).
=> SAZ-360 adds job_search to industry benchmark industries

content/api/suppression-list.apib
Ticket link: https://sparkpost.atlassian.net/browse/TR-3636
Clarify subaccount behavior of `DELETE /v1/suppresion-list/{recipient}`, since one customer was confused whether or not it would delete across the main account & subaccount in case the `X-MSYS-SUBACCOUNT` header wasn't provided
=> TR-3636 Clarify subaccount behavior of DELETE /v1/suppresion-list/{recipient}

content/api/ab-testing.apib, content/api/transmissions.apib
These banners got one of our customers confused, since `inline` frequently refers to inline template. Per suggestion of Kieran Cooper, I'm just removing the `inline` word from the banners
=> Improving AB tests warning banners

content/api/template-language.apib
SAS has complained that while using multibyte Japanese and Chinese characters in the `data-msys-linkname` field, it was getting truncated with less than 63 characters. Our documentation pointed out that the size limit for that field was 63 characters and not 63 bytes, but that was not true. The limit was indeed 63 bytes and since Japanese and Chinese characters do occupy more than 1byte each they were getting truncated. This is a documentation fix.
=> Fix the 'data-msys-linkname' size limit doc from 63 char to bytes
